// <auto-generated />
using System;
using Automat.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Automat.DAL.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20211211091453_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutomatAPI.Models.AutomatMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CurrentProdNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("MaxProductNum")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AutomatMachine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address1",
                            CurrentProdNumber = 1,
                            InventoryId = 1,
                            MaxProductNum = 1,
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address2",
                            CurrentProdNumber = 2,
                            InventoryId = 2,
                            MaxProductNum = 2,
                            Name = "Name2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address3",
                            CurrentProdNumber = 3,
                            InventoryId = 3,
                            MaxProductNum = 3,
                            Name = "Name3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address4",
                            CurrentProdNumber = 4,
                            InventoryId = 4,
                            MaxProductNum = 4,
                            Name = "Name4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address5",
                            CurrentProdNumber = 5,
                            InventoryId = 5,
                            MaxProductNum = 5,
                            Name = "Name5"
                        });
                });

            modelBuilder.Entity("AutomatAPI.Models.DiscountCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Discount")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<float>("PurchaseSum")
                        .HasMaxLength(30)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("DiscountCard");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 1,
                            PurchaseSum = 1f
                        },
                        new
                        {
                            Id = 2,
                            Discount = 2,
                            PurchaseSum = 2f
                        },
                        new
                        {
                            Id = 3,
                            Discount = 3,
                            PurchaseSum = 3f
                        },
                        new
                        {
                            Id = 4,
                            Discount = 4,
                            PurchaseSum = 4f
                        },
                        new
                        {
                            Id = 5,
                            Discount = 5,
                            PurchaseSum = 5f
                        });
                });

            modelBuilder.Entity("AutomatAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentQuantity")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceString")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Sells")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentQuantity = 0,
                            Description = "Газ",
                            Location = "Караван",
                            Name = "Вода",
                            Price = 1m,
                            PriceString = "1.00",
                            Sells = 10,
                            ShortDescription = "SD"
                        },
                        new
                        {
                            Id = 2,
                            CurrentQuantity = 0,
                            Description = "СО2",
                            Location = "Дафи",
                            Name = "Кола",
                            Price = 2m,
                            PriceString = "2.00",
                            Sells = 13,
                            ShortDescription = "SD"
                        },
                        new
                        {
                            Id = 3,
                            CurrentQuantity = 0,
                            Description = "Бутерброд",
                            Location = "Аве Плаза",
                            Name = "Снек",
                            Price = 3m,
                            PriceString = "3.00",
                            Sells = 30,
                            ShortDescription = "SD"
                        },
                        new
                        {
                            Id = 4,
                            CurrentQuantity = 0,
                            Description = "Арабика",
                            Location = "АТБ",
                            Name = "Кофе",
                            Price = 4m,
                            PriceString = "4.00",
                            Sells = 20,
                            ShortDescription = "SD"
                        },
                        new
                        {
                            Id = 5,
                            CurrentQuantity = 0,
                            Description = "Лэйс",
                            Location = "Комфи",
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            Sells = 11,
                            ShortDescription = "SD"
                        });
                });

            modelBuilder.Entity("AutomatAPI.Models.ServiceCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Discount")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ServiceCard");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 1
                        },
                        new
                        {
                            Id = 2,
                            Discount = 2
                        },
                        new
                        {
                            Id = 3,
                            Discount = 3
                        },
                        new
                        {
                            Id = 4,
                            Discount = 4
                        },
                        new
                        {
                            Id = 5,
                            Discount = 5
                        });
                });

            modelBuilder.Entity("AutomatAPI.Models.ServiceMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SMCardId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SMCardId");

                    b.ToTable("ServiceMan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Name1",
                            Surname = "Surname1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Name2",
                            Surname = "Surname2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Name3",
                            Surname = "Surname3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Name4",
                            Surname = "Surname4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Name5",
                            Surname = "Surname5"
                        });
                });

            modelBuilder.Entity("AutomatAPI.Models.Solds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceString")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("SellsDateTime")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tax")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Solds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Вода",
                            Price = 1m,
                            PriceString = "1.00",
                            SellsDateTime = new DateTime(2021, 11, 1, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кола",
                            Price = 2m,
                            PriceString = "2.00",
                            SellsDateTime = new DateTime(2021, 11, 2, 7, 20, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Снек",
                            Price = 3m,
                            PriceString = "3.00",
                            SellsDateTime = new DateTime(2021, 11, 3, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Кофе",
                            Price = 4m,
                            PriceString = "4.00",
                            SellsDateTime = new DateTime(2021, 11, 4, 7, 40, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 11, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 11, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 11, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 11, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 11, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 28,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Чипсы",
                            Price = 5m,
                            PriceString = "5.00",
                            SellsDateTime = new DateTime(2021, 12, 5, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            Tax = 20m
                        });
                });

            modelBuilder.Entity("AutomatAPI.Models.ServiceMan", b =>
                {
                    b.HasOne("AutomatAPI.Models.ServiceCard", "SMCard")
                        .WithMany()
                        .HasForeignKey("SMCardId");

                    b.Navigation("SMCard");
                });
#pragma warning restore 612, 618
        }
    }
}
